---
name: Checks

on: [push]

jobs:
  test-list:
      name: Test and Lint     
      runs-on: ubuntu-22.04
      steps:
        - name: Login to docker hub
          uses: docker/login-action@v3
          with:
              username: ${{secrets.DOCKERHUB_USER}}      
              password: ${{secrets.DOCKERHUB_TOKEN}} 
        - name: Checkout
          uses: actions/checkout@v3
        - name: Test
          run: docker-compose exec recipe-app-api-app sh -c "python manage.py test"
        - name: Lint
          run: docker-compose run --rm recipe-app-api-app sh -c "flake8" 