---
name: Checks

#this is the trigger
#this piece of code is for github actions => when we push sth to github it pushes that data automatically to the container we made in dockerhub  
on: [push]
jobs:
  test-list:
    - name: Test and Lint     
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout code
          uses: docker/login-action@1
          with:
              name: ${{secret.DOCKERHUB_USER}}      
              password: ${{secret.DOCKERHUB_TOKEN}} 
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test
          run: docker-compose run --rm app sh -c "python manage.py test"
        - name: Lint
          run: docker-compose run --rm sh -c "flake8" 
